version: '3.8'
services:
  fold:
    build: .
    image: fold-app:latest
    container_name: fold
    working_dir: /app
    command: ["/app/fold"]
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
