services:
  fold:
    build: .
    image: fold-app:latest
    container_name: fold
    working_dir: /app
    command: /bin/sh -c "/app/wait-for-it.sh postgres:5432 -- /app/wait-for-it.sh rabbitmq:5672 -- /app/fold"
    environment:
      - FOLD_AMQP_URL=amqp://guest:guest@rabbitmq:5672/
      - FOLD_PG_URL=postgres://fold:fold@postgres:5432/fold
    depends_on:
      - rabbitmq
      - postgres
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      - POSTGRES_USER=fold
      - POSTGRES_PASSWORD=fold
      - POSTGRES_DB=fold
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
