services:
  fold_worker:
    build:
      context: .
      dockerfile: Dockerfile.fold_worker
    image: fold-worker-app:latest
    container_name: fold_worker
    working_dir: /app
    command: sh -c "/app/wait-for-it.sh postgres:5432 --timeout=30 -- /app/wait-for-it.sh rabbitmq:5672 --timeout=30 -- /app/wait-for-it.sh minio:9000 --timeout=30 -- /app/fold_worker"
    environment:
      - FOLD_AMQP_URL=amqp://guest:guest@rabbitmq:5672/
      - FOLD_PG_URL=postgres://fold:fold@postgres:5432/fold
      - FOLD_INTERNER_BLOB_ENDPOINT=http://minio:9000
      - FOLD_INTERNER_BLOB_ACCESS_KEY=minioadmin
      - FOLD_INTERNER_BLOB_SECRET_KEY=minioadmin
      - FOLD_MODE=distributed
      - FOLD_INTERNER_BLOB_BUCKET=internerdata
    depends_on:
      - rabbitmq
      - postgres
      - minio
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      - POSTGRES_USER=fold
      - POSTGRES_PASSWORD=fold
      - POSTGRES_DB=fold
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  minio:
    image: minio/minio
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - miniostorage:/data
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686"   # Jaeger UI
      - "4317:4317"     # OTLP gRPC ingest
      - "4318:4318"     # OTLP HTTP ingest
      - "6831:6831/udp" # Jaeger agent UDP (optional)
      - "14268:14268"   # Jaeger collector HTTP (optional)
  follower:
    build:
      context: .
      dockerfile: Dockerfile.follower
    image: fold_follower:latest
    depends_on:
      - rabbitmq
    environment:
      - FOLD_MODE=distributed
      - FOLD_AMQP_URL=amqp://guest:guest@rabbitmq:5672/
      - FOLD_PG_URL=postgres://fold:fold@postgres:5432/fold
      - FOLD_INTERNER_BLOB_ENDPOINT=http://minio:9000
      - FOLD_INTERNER_BLOB_ACCESS_KEY=minioadmin
      - FOLD_INTERNER_BLOB_SECRET_KEY=minioadmin
      - FOLD_INTERNER_BLOB_BUCKET=internerdata
    command: ["/app/wait-for-it.sh", "rabbitmq:5672", "--", "/app/follower"]
  feeder:
    build:
      context: .
      dockerfile: Dockerfile.feeder
    image: fold_feeder:latest
    container_name: feeder
    working_dir: /app
    command: sh -c "/app/wait-for-it.sh rabbitmq:5672 --timeout=30 -- /app/feeder"
    environment:
      - FOLD_MODE=distributed
      - FOLD_AMQP_URL=amqp://guest:guest@rabbitmq:5672/
      - FOLD_PG_URL=postgres://fold:fold@postgres:5432/fold
      - FOLD_INTERNER_BLOB_ENDPOINT=http://minio:9000
      - FOLD_INTERNER_BLOB_ACCESS_KEY=minioadmin
      - FOLD_INTERNER_BLOB_SECRET_KEY=minioadmin
      - FOLD_INTERNER_BLOB_BUCKET=internerdata
    depends_on:
      - rabbitmq
      - postgres
      - minio
  ingestor:
    build:
      context: .
      dockerfile: Dockerfile.ingestor
    image: fold-ingestor:latest
    container_name: ingestor
    working_dir: /app
    entrypoint: ""
    command: ""
    environment:
      - FOLD_AMQP_URL=amqp://guest:guest@rabbitmq:5672/
      - FOLD_PG_URL=postgres://fold:fold@postgres:5432/fold
      - FOLD_INTERNER_BLOB_ENDPOINT=http://minio:9000
      - FOLD_INTERNER_BLOB_ACCESS_KEY=minioadmin
      - FOLD_INTERNER_BLOB_SECRET_KEY=minioadmin
      - FOLD_MODE=distributed
      - FOLD_INTERNER_BLOB_BUCKET=internerdata
    depends_on:
      - rabbitmq
      - postgres
      - minio
    profiles:
      - manual

volumes:
  pgdata:
  internerdata:
  miniostorage:
